#disable root login
---
- name: Disable root login
  hosts: all
  become: true

  tasks:
    - name: Set PermitRootLogin to no in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted



#fail to ban 
---
- name: Install Fail2ban
  hosts: all
  become: true

  tasks:
    - name: Install Fail2ban package
      package:
        name: fail2ban
        state: latest

    - name: Copy jail.local configuration file
      template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

# [sshd]
# enabled = true
# port = ssh
# filter = sshd
# logpath = /var/log/secure
# maxretry = 3
# bantime = 86400

#unopened ports
---
- name: Close unused ports
  hosts: all
  become: true

  tasks:
    - name: Get list of listening ports
      shell: 'ss -tln | awk "NR>1{print \$4}" | awk -F":" "{print \$NF}" | sort -u'
      register: listening_ports

    - name: Set firewall rules
      firewalld:
        port: '{{ item }}/tcp'
        state: enabled
      with_items: "{{ all_ports | difference(listening_ports.stdout_lines) }}"
      vars:
        all_ports:
          - 20
          - 21
          - 22
          - 25
          - 53
          - 80
          - 110
          - 143
          - 443
          - 465
          - 587
          - 993
          - 995

    - name: Reload firewall
      service:
        name: firewalld
        state: reloaded

#dos attack
---
- name: Prevent DoS attacks
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - fail2ban
        - sysstat
        - iptables

    - name: Configure fail2ban
      template:
        src: fail2ban.j2
        dest: /etc/fail2ban/fail2ban.conf
        mode: 0600
      notify: restart fail2ban

    - name: Configure sysstat
      lineinfile:
        path: /etc/cron.d/sysstat
        line: '*/5 * * * * root /usr/lib64/sa/sa1 1 1'
      notify: restart sysstat

    - name: Configure iptables
      template:
        src: iptables.j2
        dest: /etc/sysconfig/iptables
        mode: 0600
      notify: restart iptables

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

    - name: restart sysstat
      service:
        name: sysstat
        state: restarted

    - name: restart iptables
      service:
        name: iptables
        state: restarted

